### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by piwawa** [jtagcat/demucs-web#8]
Any screenshot for your web?

**Comment by jtagcat** [comment]
![image](https://github.com/jtagcat/demucs-web/assets/38327267/22899b59-66e6-48ef-8afb-f41e45b537ae)

![image](https://github.com/jtagcat/demucs-web/assets/38327267/076f1c4a-753f-485d-93b0-4ccad2aabf57)

**Comment by jtagcat** [comment]
Deploy with docker (details in https://github.com/jtagcat/demucs-web/blob/main/README.md), example docker-compose:

```
services:
  demucs-web:
    build: https://github.com/jtagcat/demucs-web.git#main
    volumes:
      - /my/demucs-data:/wd/data:rw
    environment:
      WORKERS: 1
      TIMEOUT: 1h
      JOBS_HTDEMUCS_FT: 6
      JOBS_HTDEMUCS_6S: 6
      JOBS_HDEMUCS_MMI: 12
      JOBS_MDX_EXTRA: 12
    ports:
      - 127.0.0.1:8080:8080
    restart: unless-stopped
```
